"""
TYRE locale registry — Python mirror of @tyre/i18n/src/locales.ts.

This file is AUTO-GENERATED by scripts/sync-locales.ts on every commit.
DO NOT EDIT MANUALLY — edit the TypeScript source and re-run sync.
"""
from dataclasses import dataclass
from enum import Enum


class Tier(int, Enum):
    T1 = 1
    T2 = 2
    T3 = 3
    T4 = 4


class Direction(str, Enum):
    LTR = 'ltr'
    RTL = 'rtl'


@dataclass(frozen=True)
class LocaleConfig:
    code: str
    name: str
    native_name: str
    iso639_3: str
    region: str
    tier: Tier
    direction: Direction
    voice_enabled: bool
    stt_enabled: bool
    mt_enabled: bool
    fallback: str | None = None


LOCALES: list[LocaleConfig] = [
    LocaleConfig('hi', 'Hindi', 'हिन्दी', 'hin', 'IN', Tier.T1, Direction.LTR, True, True, True, fallback='en'),
    LocaleConfig('en', 'English', 'English', 'eng', 'IN', Tier.T1, Direction.LTR, True, True, True),
    LocaleConfig('bn', 'Bengali', 'বাংলা', 'ben', 'IN', Tier.T1, Direction.LTR, True, True, True, fallback='en'),
    LocaleConfig('te', 'Telugu', 'తెలుగు', 'tel', 'IN', Tier.T1, Direction.LTR, True, True, True, fallback='en'),
    LocaleConfig('mr', 'Marathi', 'मराठी', 'mar', 'IN', Tier.T1, Direction.LTR, True, True, True, fallback='en'),
    LocaleConfig('ta', 'Tamil', 'தமிழ்', 'tam', 'IN', Tier.T1, Direction.LTR, True, True, True, fallback='en'),
    LocaleConfig('ur', 'Urdu', 'اُردُو', 'urd', 'IN', Tier.T1, Direction.RTL, True, True, True, fallback='en'),
    LocaleConfig('gu', 'Gujarati', 'ગુજરાતી', 'guj', 'IN', Tier.T1, Direction.LTR, True, True, True, fallback='en'),
    LocaleConfig('kn', 'Kannada', 'ಕನ್ನಡ', 'kan', 'IN', Tier.T1, Direction.LTR, True, True, True, fallback='en'),
    LocaleConfig('or', 'Odia', 'ଓଡ଼ିଆ', 'ory', 'IN', Tier.T1, Direction.LTR, True, True, True, fallback='en'),
    LocaleConfig('ml', 'Malayalam', 'മലയാളം', 'mal', 'IN', Tier.T1, Direction.LTR, True, True, True, fallback='en'),
    LocaleConfig('pa', 'Punjabi', 'ਪੰਜਾਬੀ', 'pan', 'IN', Tier.T1, Direction.LTR, True, True, True, fallback='en'),
    LocaleConfig('as', 'Assamese', 'অসমীয়া', 'asm', 'IN', Tier.T1, Direction.LTR, True, True, True, fallback='en'),
    LocaleConfig('sw', 'Swahili', 'Kiswahili', 'swh', 'KE', Tier.T1, Direction.LTR, True, True, True, fallback='en'),
    LocaleConfig('ha', 'Hausa', 'Hausa', 'hau', 'NG', Tier.T1, Direction.LTR, True, True, True, fallback='en'),
    LocaleConfig('pt-BR', 'Portuguese (Brazil)', 'Português (Brasil)', 'por', 'BR', Tier.T1, Direction.LTR, True, True, True, fallback='en'),
    LocaleConfig('es-MX', 'Spanish (Mexico)', 'Español (México)', 'spa', 'MX', Tier.T1, Direction.LTR, True, True, True, fallback='en'),
    LocaleConfig('ar', 'Arabic', 'العربية', 'arb', 'AE', Tier.T1, Direction.RTL, True, True, True, fallback='en'),
    LocaleConfig('ne', 'Nepali', 'नेपाली', 'npi', 'NP', Tier.T1, Direction.LTR, True, True, True, fallback='hi'),
    LocaleConfig('si', 'Sinhala', 'සිංහල', 'sin', 'LK', Tier.T1, Direction.LTR, True, True, True, fallback='en'),
    LocaleConfig('bho', 'Bhojpuri', 'भोजपुरी', 'bho', 'IN', Tier.T2, Direction.LTR, False, True, True, fallback='hi'),
    LocaleConfig('mag', 'Magahi', 'मगही', 'mag', 'IN', Tier.T2, Direction.LTR, False, True, True, fallback='hi'),
    LocaleConfig('ang', 'Angika', 'अंगिका', 'anp', 'IN', Tier.T2, Direction.LTR, False, True, True, fallback='bho'),
    LocaleConfig('mai', 'Maithili', 'मैथिली', 'mai', 'IN', Tier.T2, Direction.LTR, False, True, True, fallback='hi'),
    LocaleConfig('hne', 'Chhattisgarhi', 'छत्तीसगढ़ी', 'hne', 'IN', Tier.T2, Direction.LTR, False, True, True, fallback='hi'),
    LocaleConfig('awa', 'Awadhi', 'अवधी', 'awa', 'IN', Tier.T2, Direction.LTR, False, True, True, fallback='hi'),
    LocaleConfig('bgc', 'Haryanvi', 'हरियाणवी', 'bgc', 'IN', Tier.T2, Direction.LTR, False, True, True, fallback='hi'),
    LocaleConfig('bns', 'Bundeli', 'बुन्देली', 'bns', 'IN', Tier.T2, Direction.LTR, False, True, True, fallback='hi'),
    LocaleConfig('mwr', 'Marwari', 'मारवाड़ी', 'mwr', 'IN', Tier.T2, Direction.LTR, False, True, True, fallback='hi'),
    LocaleConfig('raj', 'Rajasthani', 'राजस्थानी', 'raj', 'IN', Tier.T2, Direction.LTR, False, True, True, fallback='hi'),
    LocaleConfig('gbm', 'Garhwali', 'गढ़वाली', 'gbm', 'IN', Tier.T2, Direction.LTR, False, True, True, fallback='hi'),
    LocaleConfig('kfy', 'Kumaoni', 'कुमाऊँनी', 'kfy', 'IN', Tier.T2, Direction.LTR, False, True, True, fallback='hi'),
    LocaleConfig('tcy', 'Tulu', 'ತುಳು', 'tcy', 'IN', Tier.T2, Direction.LTR, False, True, True, fallback='kn'),
    LocaleConfig('kfa', 'Kodava', 'ಕೊಡವ', 'kfa', 'IN', Tier.T2, Direction.LTR, False, False, True, fallback='kn'),
    LocaleConfig('kok', 'Konkani', 'कोंकणी', 'kok', 'IN', Tier.T2, Direction.LTR, False, True, True, fallback='mr'),
    LocaleConfig('ks', 'Kashmiri', 'कॉशुर', 'kas', 'IN', Tier.T2, Direction.RTL, False, True, True, fallback='ur'),
    LocaleConfig('dgo', 'Dogri', 'डोगरी', 'dgo', 'IN', Tier.T2, Direction.LTR, False, True, True, fallback='hi'),
    LocaleConfig('mni', 'Manipuri', 'মেইতেই লোন্', 'mni', 'IN', Tier.T2, Direction.LTR, False, True, True, fallback='bn'),
    LocaleConfig('sat', 'Santali', 'ᱥᱟᱱᱛᱟᱲᱤ', 'sat', 'IN', Tier.T2, Direction.LTR, False, True, True, fallback='bn'),
    LocaleConfig('brx', 'Bodo', 'बड़ो', 'brx', 'IN', Tier.T2, Direction.LTR, False, True, True, fallback='as'),
    LocaleConfig('grt', 'Garo', 'A·chik', 'grt', 'IN', Tier.T2, Direction.LTR, False, False, True, fallback='en'),
    LocaleConfig('kha', 'Khasi', 'Ka Ktien Khasi', 'kha', 'IN', Tier.T2, Direction.LTR, False, False, True, fallback='en'),
    LocaleConfig('lus', 'Mizo', 'Mizo ṭawng', 'lus', 'IN', Tier.T2, Direction.LTR, False, True, True, fallback='en'),
    LocaleConfig('nag', 'Nagamese', 'Nagamese', 'nag', 'IN', Tier.T2, Direction.LTR, False, False, True, fallback='en'),
    LocaleConfig('trp', 'Kokborok', 'ককবরক', 'trp', 'IN', Tier.T2, Direction.LTR, False, False, True, fallback='bn'),
    LocaleConfig('bhb', 'Bhili', 'भीली', 'bhb', 'IN', Tier.T2, Direction.LTR, False, False, True, fallback='gu'),
    LocaleConfig('gon', 'Gondi', 'గోండి', 'gon', 'IN', Tier.T2, Direction.LTR, False, False, True, fallback='te'),
    LocaleConfig('hoc', 'Ho', 'ᱦᱚ', 'hoc', 'IN', Tier.T2, Direction.LTR, False, False, True, fallback='sat'),
    LocaleConfig('unr', 'Mundari', 'ᱢᱩᱱᱰᱟᱹᱨᱤ', 'unr', 'IN', Tier.T2, Direction.LTR, False, False, True, fallback='sat'),
    LocaleConfig('kru', 'Kurukh', 'कुड़ुख', 'kru', 'IN', Tier.T2, Direction.LTR, False, False, True, fallback='hi'),
    LocaleConfig('sck', 'Sadri', 'सदरी', 'sck', 'IN', Tier.T2, Direction.LTR, False, True, True, fallback='hi'),
    LocaleConfig('sjp', 'Surjapuri', 'सुरजापुरी', 'sjp', 'IN', Tier.T2, Direction.LTR, False, False, True, fallback='bho'),
    LocaleConfig('dak', 'Dakhini', 'دکنی', 'dak', 'IN', Tier.T2, Direction.RTL, False, True, True, fallback='ur'),
    LocaleConfig('lmn', 'Lambadi', 'लम्बाडी', 'lmn', 'IN', Tier.T2, Direction.LTR, False, False, True, fallback='te'),
    LocaleConfig('sa', 'Sanskrit', 'संस्कृतम्', 'san', 'IN', Tier.T2, Direction.LTR, False, False, True, fallback='hi'),
    LocaleConfig('sd', 'Sindhi', 'سنڌي', 'snd', 'IN', Tier.T2, Direction.RTL, False, True, True, fallback='ur'),
    LocaleConfig('bn-BD', 'Bengali (Bangladesh)', 'বাংলা (বাংলাদেশ)', 'ben', 'BD', Tier.T3, Direction.LTR, False, True, True, fallback='bn'),
    LocaleConfig('ps', 'Pashto', 'پښتو', 'pus', 'PK', Tier.T3, Direction.RTL, False, True, True, fallback='ur'),
    LocaleConfig('si-LK', 'Sinhala (LK)', 'සිංහල', 'sin', 'LK', Tier.T3, Direction.LTR, False, True, True, fallback='si'),
    LocaleConfig('dv', 'Dhivehi', 'ދިވެހި', 'div', 'MV', Tier.T3, Direction.RTL, False, False, True, fallback='en'),
    LocaleConfig('yo', 'Yoruba', 'Yorùbá', 'yor', 'NG', Tier.T3, Direction.LTR, True, True, True, fallback='en'),
    LocaleConfig('ig', 'Igbo', 'Igbo', 'ibo', 'NG', Tier.T3, Direction.LTR, False, True, True, fallback='en'),
    LocaleConfig('am', 'Amharic', 'አማርኛ', 'amh', 'ET', Tier.T3, Direction.LTR, True, True, True, fallback='en'),
    LocaleConfig('zu', 'Zulu', 'isiZulu', 'zul', 'ZA', Tier.T3, Direction.LTR, False, True, True, fallback='en'),
    LocaleConfig('xh', 'Xhosa', 'isiXhosa', 'xho', 'ZA', Tier.T3, Direction.LTR, False, True, True, fallback='en'),
    LocaleConfig('af', 'Afrikaans', 'Afrikaans', 'afr', 'ZA', Tier.T3, Direction.LTR, False, True, True, fallback='en'),
    LocaleConfig('rw', 'Kinyarwanda', 'Kinyarwanda', 'kin', 'RW', Tier.T3, Direction.LTR, False, True, True, fallback='en'),
    LocaleConfig('fr', 'French', 'Français', 'fra', 'CI', Tier.T3, Direction.LTR, True, True, True, fallback='en'),
    LocaleConfig('fr-CI', 'French (Côte d\'Ivoire)', 'Français (Côte d\'Ivoire)', 'fra', 'CI', Tier.T3, Direction.LTR, False, True, True, fallback='fr'),
    LocaleConfig('fr-SN', 'French (Senegal)', 'Français (Sénégal)', 'fra', 'SN', Tier.T3, Direction.LTR, False, True, True, fallback='fr'),
    LocaleConfig('wo', 'Wolof', 'Wolof', 'wol', 'SN', Tier.T3, Direction.LTR, False, False, True, fallback='fr-SN'),
    LocaleConfig('so', 'Somali', 'Soomaali', 'som', 'SO', Tier.T3, Direction.LTR, False, True, True, fallback='ar'),
    LocaleConfig('es-CO', 'Spanish (Colombia)', 'Español (Colombia)', 'spa', 'CO', Tier.T3, Direction.LTR, False, True, True, fallback='es-MX'),
    LocaleConfig('es-PE', 'Spanish (Peru)', 'Español (Perú)', 'spa', 'PE', Tier.T3, Direction.LTR, False, True, True, fallback='es-MX'),
    LocaleConfig('es-AR', 'Spanish (Argentina)', 'Español (Argentina)', 'spa', 'AR', Tier.T3, Direction.LTR, False, True, True, fallback='es-MX'),
    LocaleConfig('qu', 'Quechua', 'Runa Simi', 'que', 'PE', Tier.T3, Direction.LTR, False, False, True, fallback='es-PE'),
    LocaleConfig('fa', 'Persian', 'فارسی', 'fas', 'IR', Tier.T3, Direction.RTL, False, True, True, fallback='ar'),
    LocaleConfig('tr', 'Turkish', 'Türkçe', 'tur', 'TR', Tier.T3, Direction.LTR, True, True, True, fallback='en'),
    LocaleConfig('he', 'Hebrew', 'עברית', 'heb', 'IL', Tier.T3, Direction.RTL, False, True, True, fallback='en'),
    LocaleConfig('id', 'Indonesian', 'Bahasa Indonesia', 'ind', 'ID', Tier.T3, Direction.LTR, True, True, True, fallback='en'),
    LocaleConfig('vi', 'Vietnamese', 'Tiếng Việt', 'vie', 'VN', Tier.T3, Direction.LTR, True, True, True, fallback='en'),
    LocaleConfig('th', 'Thai', 'ภาษาไทย', 'tha', 'TH', Tier.T3, Direction.LTR, True, True, True, fallback='en'),
    LocaleConfig('fil', 'Filipino', 'Filipino', 'fil', 'PH', Tier.T3, Direction.LTR, True, True, True, fallback='en'),
    LocaleConfig('ms', 'Malay', 'Bahasa Melayu', 'msa', 'MY', Tier.T3, Direction.LTR, False, True, True, fallback='id'),
    LocaleConfig('km', 'Khmer', 'ខ្មែរ', 'khm', 'KH', Tier.T3, Direction.LTR, False, True, True, fallback='en'),
    LocaleConfig('lo', 'Lao', 'ລາວ', 'lao', 'LA', Tier.T3, Direction.LTR, False, True, True, fallback='en'),
    LocaleConfig('my', 'Burmese', 'ဗမာ', 'mya', 'MM', Tier.T3, Direction.LTR, False, True, True, fallback='en'),
    LocaleConfig('jv', 'Javanese', 'Basa Jawa', 'jav', 'ID', Tier.T3, Direction.LTR, False, False, True, fallback='id'),
    LocaleConfig('su', 'Sundanese', 'Basa Sunda', 'sun', 'ID', Tier.T3, Direction.LTR, False, False, True, fallback='id'),
    LocaleConfig('kk', 'Kazakh', 'Қазақ', 'kaz', 'KZ', Tier.T3, Direction.LTR, False, False, True, fallback='tr'),
    LocaleConfig('ky', 'Kyrgyz', 'Кыргызча', 'kir', 'KG', Tier.T3, Direction.LTR, False, False, True, fallback='kk'),
    LocaleConfig('uz', 'Uzbek', 'Oʻzbek', 'uzb', 'UZ', Tier.T3, Direction.LTR, False, False, True, fallback='tr'),
    LocaleConfig('tk', 'Turkmen', 'Türkmen', 'tuk', 'TM', Tier.T3, Direction.LTR, False, False, True, fallback='uz'),
    LocaleConfig('tg', 'Tajik', 'Тоҷикӣ', 'tgk', 'TJ', Tier.T3, Direction.LTR, False, False, True, fallback='fa'),
    LocaleConfig('ak', 'Akan', 'Akan', 'aka', 'GH', Tier.T3, Direction.LTR, False, False, True, fallback='en'),
    LocaleConfig('ee', 'Ewe', 'Eʋegbe', 'ewe', 'GH', Tier.T3, Direction.LTR, False, False, True, fallback='ak'),
    LocaleConfig('bm', 'Bambara', 'Bamanankan', 'bam', 'ML', Tier.T3, Direction.LTR, False, False, True, fallback='fr'),
    LocaleConfig('ff', 'Fula', 'Fulfulde', 'ful', 'NG', Tier.T3, Direction.LTR, False, False, True, fallback='ha'),
    LocaleConfig('om', 'Oromo', 'Afaan Oromoo', 'orm', 'ET', Tier.T3, Direction.LTR, False, False, True, fallback='am'),
    LocaleConfig('ti', 'Tigrinya', 'ትግርኛ', 'tir', 'ET', Tier.T3, Direction.LTR, False, False, True, fallback='am'),
    LocaleConfig('lg', 'Luganda', 'Luganda', 'lug', 'UG', Tier.T3, Direction.LTR, False, False, True, fallback='en'),
    LocaleConfig('sn', 'Shona', 'chiShona', 'sna', 'ZW', Tier.T3, Direction.LTR, False, False, True, fallback='en'),
    LocaleConfig('ny', 'Chewa', 'Chichewa', 'nya', 'MW', Tier.T3, Direction.LTR, False, False, True, fallback='en'),
    LocaleConfig('ln', 'Lingala', 'Lingála', 'lin', 'CD', Tier.T3, Direction.LTR, False, False, True, fallback='fr-CD'),
    LocaleConfig('fr-CD', 'French (DRC)', 'Français (RDC)', 'fra', 'CD', Tier.T3, Direction.LTR, False, True, True, fallback='fr'),
    LocaleConfig('es-ES', 'Spanish (Spain)', 'Español (España)', 'spa', 'ES', Tier.T3, Direction.LTR, False, True, True, fallback='es-MX'),
    LocaleConfig('es-CL', 'Spanish (Chile)', 'Español (Chile)', 'spa', 'CL', Tier.T3, Direction.LTR, False, True, True, fallback='es-MX'),
    LocaleConfig('es-EC', 'Spanish (Ecuador)', 'Español (Ecuador)', 'spa', 'EC', Tier.T3, Direction.LTR, False, True, True, fallback='es-MX'),
    LocaleConfig('es-VE', 'Spanish (Venezuela)', 'Español (Venezuela)', 'spa', 'VE', Tier.T3, Direction.LTR, False, True, True, fallback='es-MX'),
    LocaleConfig('es-BO', 'Spanish (Bolivia)', 'Español (Bolivia)', 'spa', 'BO', Tier.T3, Direction.LTR, False, True, True, fallback='es-MX'),
    LocaleConfig('ay', 'Aymara', 'Aymar aru', 'aym', 'BO', Tier.T3, Direction.LTR, False, False, True, fallback='es-BO'),
    LocaleConfig('gn', 'Guarani', 'Avañeẽ', 'grn', 'PY', Tier.T3, Direction.LTR, False, False, True, fallback='es-MX'),
    LocaleConfig('ht', 'Haitian Creole', 'Kreyòl ayisyen', 'hat', 'HT', Tier.T3, Direction.LTR, False, False, True, fallback='fr'),
    LocaleConfig('zh-Hans', 'Chinese (Simplified)', '简体中文', 'zho', 'CN', Tier.T4, Direction.LTR, False, True, True, fallback='en'),
    LocaleConfig('ja', 'Japanese', '日本語', 'jpn', 'JP', Tier.T4, Direction.LTR, False, True, True, fallback='en'),
    LocaleConfig('ko', 'Korean', '한국어', 'kor', 'KR', Tier.T4, Direction.LTR, False, True, True, fallback='en'),
    LocaleConfig('ru', 'Russian', 'Русский', 'rus', 'RU', Tier.T4, Direction.LTR, False, True, True, fallback='en'),
    LocaleConfig('uk', 'Ukrainian', 'Українська', 'ukr', 'UA', Tier.T4, Direction.LTR, False, True, True, fallback='ru'),
    LocaleConfig('pl', 'Polish', 'Polski', 'pol', 'PL', Tier.T4, Direction.LTR, False, True, True, fallback='en'),
    LocaleConfig('de', 'German', 'Deutsch', 'deu', 'DE', Tier.T4, Direction.LTR, False, True, True, fallback='en'),
    LocaleConfig('it', 'Italian', 'Italiano', 'ita', 'IT', Tier.T4, Direction.LTR, False, True, True, fallback='en'),
    LocaleConfig('nl', 'Dutch', 'Nederlands', 'nld', 'NL', Tier.T4, Direction.LTR, False, True, True, fallback='en'),
    LocaleConfig('sv', 'Swedish', 'Svenska', 'swe', 'SE', Tier.T4, Direction.LTR, False, True, True, fallback='en'),
]

LOCALE_MAP = {l.code: l for l in LOCALES}
RTL_LOCALES = [l.code for l in LOCALES if l.direction == Direction.RTL]
VOICE_LOCALES = [l.code for l in LOCALES if l.voice_enabled]

def resolve_locale(code):
    if not code: return 'en'
    if code in LOCALE_MAP: return code
    subtag = '-'.join(code.split('-')[:2])
    if subtag in LOCALE_MAP: return subtag
    lang = code.split('-')[0]
    for l in LOCALES:
        if l.code == lang or l.code.startswith(lang + '-'): return l.code
    return 'en'

# Aliases — voice/speech modules import these names (AI-C2 fix)
resolve_stt_locale = resolve_locale
resolve_voice_locale = resolve_locale
resolve_mt_locale = resolve_locale
resolveSTTLocale = resolve_locale
resolveVoiceLocale = resolve_locale
resolveMTLocale = resolve_locale
